wpensar_erp_colaborador_listar:
    pattern:  /colaboradores
    defaults: { _controller: WPensarERPBundle:Colaborador:index }
    
wpensar_erp_colaborador_cadastrar:
    pattern:  /colaborador/cadastrar
    defaults: { _controller: WPensarERPBundle:Colaborador:cadastrar }
    
wpensar_erp_colaborador_editar:
    pattern:  /colaborador/editar/{id}
    defaults: { _controller: WPensarERPBundle:Colaborador:editar }
    
wpensar_erp_colaborador_excluir:
    pattern:  /colaborador/excluir/{id}
    defaults: { _controller: WPensarERPBundle:Colaborador:excluir }
    
login:
    pattern:   /login
    defaults:  { _controller: WPensarERPBundle:Colaborador:login }
    
login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
