<?php

namespace WPensar\ERPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColaboradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColaboradorRepository extends EntityRepository
{
}
