jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        WPensar\ERPBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: WPensarERPBundle:User, property: username }

    firewalls:
      
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern:  ^/demo/secured/login$
#            security: false

        admin_area:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: wpensar_erp_colaborador_listar
                always_use_default_target_path: true
                use_referer: true
            logout: ~
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
